### ISSUE TITLE
Latest tag in Docker hub does not match latest release

### ISSUE THREAD

**Issue by diemol** [saucelabs/sauce-puppeteer-runner#21]
If we want to open source this repository, the latest release should match the `latest` tag in Docker hub. Otherwise, users will be pulling images with `latest` and this does not match any of the releases.

Latest release
https://github.com/saucelabs/sauce-puppeteer-runner/releases/tag/v0.1.4
Matching tag in Docker hub
https://hub.docker.com/layers/saucelabs/stt-puppeteer-jest-node/v0.1.4/images/sha256-a8bde7f21f43d57decea9853dd19e89d855bf91bc32d76a609f76df4aa2bf62d?context=explore

`latest` in Docker hub has a different SHA
https://hub.docker.com/layers/saucelabs/stt-puppeteer-jest-node/latest/images/sha256-c4bf924bb8a9aca0aa0f30cdac9ee09c3c5b2fb914900daa35e3a9c1e4a33a5f?context=explore

**Comment by vrunoa** [comment]
@diemol got PRs for each repository fixing this:
* https://github.com/saucelabs/sauce-cypress-runner/pull/16
* https://github.com/saucelabs/sauce-puppeteer-runner/pull/25
* https://github.com/saucelabs/sauce-testcafe-runner/pull/10
* https://github.com/saucelabs/sauce-playwright-runner/pull/22
Newest releases will have all image to reference to proper SHA

**Comment by christian-bromann** [comment]
Changes to the pipelines have been applied, thanks @vrunoa !
